cmscript: update after setup

diff --git a/home/.chezmoiscripts/run_after_00setup.sh.tmpl b/home/.chezmoiscripts/run_after_00setup.sh.tmpl
--- a/home/.chezmoiscripts/run_after_00setup.sh.tmpl
+++ b/home/.chezmoiscripts/run_after_00setup.sh.tmpl
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 . {{ joinPath .chezmoi.workingTree "/misc/utils.sh" }}
-log "* start after setup" 
+log "* [Post] START AFTER SETUP" 
 # I'm not sure why we need to do there, even though i've cleanup all .bashrc related in $HOME
 {{- if (eq .chezmoi.os "linux") }}
 if [ -f "/etc/bash.bashrc" ]; then
@@ -24,19 +24,41 @@ sudo sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.con
 
 # Use all cores for compilation.
 sudo sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf
+ 
+# Enable tap to click
+if [ ! -f "/etc/X11/xorg.conf.d/40-libinput.conf" ]; then
+	cat <<- 'EOF' | sudo tee /etc/X11/xorg.conf.d/40-libinput.conf >/dev/null; log "[Post] Enabled touchpad tap to click"
+	Section "InputClass"
+        Identifier "libinput touchpad catchall"
+        MatchIsTouchpad "on"
+        MatchDevicePath "/dev/input/event*"
+        Driver "libinput"
+        # Enable left mouse button by tapping
+        Option "Tapping" "on"
+	EndSection
+	EOF
+fi
+
 {{- end }}
 {{- if (eq .osid "linux-arch") }}
 # Profile?
-if [ -d "$HOME/.local/src/dwmf" ]; then
+# dwm
+if [ -d "$HOME/.local/src/dwmf" ] && [ -x $(command -v "dwmf") ]; then
 	sudo pacman --noconfirm -S xorg-xsetroot >/dev/null 2>&1
-	sudo make -C "$HOME/.local/src/dwmf" install | log || err "Can't build dwm"
+	sudo make -C "$HOME/.local/src/dwmf" install | log || err "[Post] Can't build dwm"
+fi
+
+# Dwmblocks
+if [ -d "$HOME/.local/src/dwmblocks-async" ] && [ -x $(command -v "dwmblocks") ]; then
+	# sudo pacman --noconfirm -S xorg-xsetroot >/dev/null 2>&1
+	sudo make -C "$HOME/.local/src/dwmblocks-async" install | log || err "[Post] Can't build dwm"
 fi
 {{- end }}
 
 case "$SHELL" in
 	*bash*)
-		sudo chsh -s /bin/zsh "$USER" >/dev/null 2>&1 & _spinner "Change Default shell to zsh" && suc "You need to relogout to takes effects"
-		log "Change default shell to zsh"
+		sudo chsh -s /bin/zsh "$USER" >/dev/null 2>&1 & _spinner "[Post] Change Default shell to zsh" && suc "You need to relogout to takes effects"
+		log "[Post] Change default shell to zsh"
 		;;
 esac
 
@@ -45,7 +67,7 @@ esac
 if [ -x "$(command -v "open-in-mpv")" ]; then
 	desktop_dir="$HOME/.local/share/applications"
 
-	cat << 'EOF' > $desktop_dir/open-in-mpv.desktop
+	cat << 'EOF' > $desktop_dir/open-in-mpv.desktop | log "[Post] Add open-in-mpv.desktop"
 [Desktop Entry]
 Name=open-in-mpv
 Exec=open-in-mpv %u
@@ -60,10 +82,10 @@ fi
 
 # Browse extension for buku
 if [ -x "$(command -v "bukubrow")" ]; then
-	bukubrow --install-brave
+	bukubrow --install-brave >/dev/null | log "[Post] Install bukubrow for brave"
 fi
 # TLDR
 if [ -x "$(command -v "tldr")" ]; then
-	tldr --print-completion zsh | tee $HOME/.config/zsh/completions/_tldr
+	tldr --print-completion zsh | tee $HOME/.config/zsh/completions/_tldr >/dev/null | log "[Post] Install tldr completion"
 fi
 {{- end }}
